version: "3.4"
services:
  monolith:
    hostname: monolith
    image: matrixdotorg/dendrite-monolith:latest
    command: [
      "--tls-cert=server.crt",
      "--tls-key=server.key"
    ]
    ports:
      - 8888:8008
      - 8889:8448
    volumes:
      - ./config:/etc/dendrite
      - ./media:/var/dendrite/media
    networks:
      - internal

networks:
  internal:
    attachable: true
